import { useState } from 'react';

const WHATSAPP = 'https://wa.me/77007101801?text=' + encodeURIComponent('Здравствуйте! Хочу получить консультацию юриста ADALTIREK.');
const services = [['01', 'Для бизнеса', 'Договорная работа, регистрация и сопровождение компаний, взыскание задолженности, защита интересов в госорганах и суде.'], ['02', 'Семейное право', 'Развод, алименты, раздел имущества, определение места жительства детей и наследственные вопросы.'], ['03', 'Трудовые споры', 'Защита работников и работодателей: увольнения, взыскания, трудовые договоры и проверки.'], ['04', 'Судебное представительство', 'Готовим правовую позицию, документы и представляем интересы доверителя на всех этапах дела.']];
const advantages = [['◈', 'Практический опыт', 'Берёмся за задачи, в которых важны точность, сроки и результат.'], ['◎', 'Конфиденциальность', 'Ваша информация и обстоятельства дела остаются строго между нами.'], ['↗', 'Понятный процесс', 'Объясняем ход дела простым языком и всегда остаёмся на связи.'], ['✓', 'Персональный подход', 'Не используем шаблонные решения — изучаем детали каждой ситуации.'], ['⌁', 'Прозрачная стоимость', 'Согласовываем объём работ и цену до начала сотрудничества.'], ['□', 'Ответственность', 'Контролируем сроки и информируем о каждом значимом шаге.']];
function Arrow() { return <span className="arrow" aria-hidden="true">↗</span>; }

export default function App() {
  const [form, setForm] = useState({ name: '', phone: '', email: '', message: '', consent: false });
  const [status, setStatus] = useState({ type: '', message: '' });
  const [menuOpen, setMenuOpen] = useState(false);
  const change = ({ target }) => setForm((value) => ({ ...value, [target.name]: target.type === 'checkbox' ? target.checked : target.value }));
  const closeMenu = () => setMenuOpen(false);
  const submit = async (event) => {
    event.preventDefault();
    if (!form.name.trim() || !form.phone.trim() || !form.consent) { setStatus({ type: 'error', message: 'Укажите имя, телефон и подтвердите согласие на обработку данных.' }); return; }
    try {
      const response = await fetch('/api/contacts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
      if (!response.ok) throw new Error('submit failed');
      setStatus({ type: 'success', message: 'Спасибо! Мы свяжемся с вами в ближайшее время.' });
      setForm({ name: '', phone: '', email: '', message: '', consent: false });
    } catch { setStatus({ type: 'error', message: 'Не удалось отправить заявку. Позвоните нам по телефону +7 (700) 710-18-01.' }); }
  };
  return <>
    <header className="header"><div className="shell header-inner"><a className="brand" href="#top" onClick={closeMenu}><img className="brand-logo" src="/assets/adaltirek-logo.jpg" alt="Логотип ADALTIREK" /><span>ADALTIREK<small>LAW FIRM</small></span></a><button className="menu-button" aria-label="Открыть меню" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><i></i><i></i></button><nav className={menuOpen ? 'nav is-open' : 'nav'}><a href="#services" onClick={closeMenu}>Услуги</a><a href="#prices" onClick={closeMenu}>Цены</a><a href="#contacts" onClick={closeMenu}>Контакты</a></nav><a className="header-phone" href="tel:+77007101801"><span>Позвоните нам</span>+7 (700) 710-18-01</a></div></header>
    <main id="top">
      <section className="hero"><div className="shell hero-content"><p className="overline light">Юридическая компания в Казахстане</p><h1>Защищаем ваши<br /><em>права и интересы.</em></h1><p className="hero-text">Предоставляем понятную и надёжную юридическую помощь для бизнеса и частных лиц.</p><div className="hero-actions"><a className="button button-gold" href={WHATSAPP} target="_blank" rel="noreferrer">Написать в WhatsApp <Arrow /></a><a className="hero-link" href="#contacts">Записаться на консультацию</a></div></div><div className="hero-note">Работаем по всему Казахстану <span>•</span> Конфиденциально <span>•</span> С заботой о результате</div></section>
      <section className="intro shell"><div><p className="overline">О компании</p><h2>Юридическая поддержка,<br />на которую можно <em>опереться.</em></h2></div><div className="intro-copy"><p>ADALTIREK помогает разобраться в сложных правовых вопросах и уверенно отстоять свою позицию.</p><p>Мы сопровождаем сделки и бизнес-процессы, решаем семейные и трудовые споры, ведём дела в суде и государственных органах.</p><a href="#services" className="text-link">Смотреть направления <Arrow /></a></div></section>
      <section className="stats"><div className="shell stats-grid"><div><strong>10<sup>+</sup></strong><span>лет юридической практики</span></div><div><strong>150<sup>+</sup></strong><span>дел сопровождаем ежегодно</span></div><div><strong>95<sup>%</sup></strong><span>клиентов рекомендуют нас</span></div></div></section>
      <section className="section shell" id="services"><div className="section-heading"><div><p className="overline">Направления работы</p><h2>Решаем правовые задачи<br /><em>любой сложности.</em></h2></div><p>Выберите нужное направление — на консультации разберём вашу ситуацию и предложим план действий.</p></div><div className="services-grid">{services.map(([number, title, text]) => <article className="service-card" key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{text}</p><a href="#contacts" aria-label={`Подробнее: ${title}`}><Arrow /></a></article>)}</div></section>
      <section className="promise"><div className="shell promise-grid"><p className="overline light">Наш принцип</p><blockquote>«Закон работает, когда<br />его применяют <em>вовремя</em><br />и профессионально».</blockquote><p className="promise-copy">Мы не обещаем невозможного. Мы внимательно изучаем обстоятельства, честно оцениваем перспективы и используем все законные способы для защиты ваших интересов.</p></div></section>
      <section className="section shell"><div className="section-heading compact"><div><p className="overline">Преимущества</p><h2>Делаем право<br /><em>понятным и доступным.</em></h2></div></div><div className="advantages-grid">{advantages.map(([icon, title, text]) => <article key={title}><span className="advantage-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="pricing" id="prices"><div className="shell pricing-inner"><div><p className="overline light">Стоимость услуг</p><h2>Честная цена<br />за <em>реальную работу.</em></h2></div><div><p>Стоимость зависит от категории дела и объёма работы. На первой консультации мы оценим вашу ситуацию и зафиксируем условия сотрудничества.</p><a href="#contacts" className="button button-outline">Узнать стоимость <Arrow /></a></div></div></section>
      <section className="contact-section" id="contacts"><div className="shell contact-layout"><div className="contact-copy"><p className="overline">Консультация</p><h2>Обсудим вашу<br /><em>ситуацию.</em></h2><p>Оставьте заявку — мы перезвоним, уточним детали и подскажем, с чего начать.</p><div className="contact-direct"><span>Телефон</span><a href="tel:+77007101801">+7 (700) 710-18-01</a><span>E-mail</span><a href="mailto:adaltirek@gmail.com">adaltirek@gmail.com</a></div></div><form className="lead-form" onSubmit={submit}><label>Ваше имя<input name="name" value={form.name} onChange={change} placeholder="Как к вам обращаться?" /></label><label>Телефон<input name="phone" value={form.phone} onChange={change} placeholder="+7 (___) ___-__-__" inputMode="tel" /></label><label>E-mail <small>необязательно</small><input name="email" value={form.email} onChange={change} placeholder="example@mail.com" type="email" /></label><label>Коротко опишите вопрос<textarea name="message" value={form.message} onChange={change} placeholder="Например: нужна помощь с договором..." rows="3" /></label><label className="consent"><input type="checkbox" name="consent" checked={form.consent} onChange={change} /><span>Я согласен(-на) на обработку персональных данных</span></label><button className="button button-dark" type="submit">Отправить заявку <Arrow /></button>{status.message && <p className={`form-status ${status.type}`}>{status.message}</p>}</form></div></section>
    </main>
    <footer><div className="shell footer-inner"><a className="brand footer-brand" href="#top"><img className="brand-logo" src="/assets/adaltirek-logo.jpg" alt="Логотип ADALTIREK" /><span>ADALTIREK<small>LAW FIRM</small></span></a><p>© {new Date().getFullYear()} ADALTIREK. Юридическая компания.</p><a href="#top">Наверх ↑</a></div></footer><a className="whatsapp-float" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label="Написать в WhatsApp">◔</a>
  </>;
}
